### ISSUE TITLE
<li> Generated outside <ul> && css does not work

### ISSUE THREAD

**Issue by songqikong** [allejo/jekyll-toc#71]
**Markdown Engine**

kramdown

**My Markdown**

```markdown
## Ⅰ Abstract
## Ⅱ Introduction:
#### Contributions:
## Ⅲ SnowflakeNet
### 3.1 Overview

#### a. Feature extraction module
#### b. Seed generation module
#### c. Point generation module
.......
```

**TOC Usage**

```twig
    <div class='col-md-2 col-xs-0'>
        <div class="toc">
          {% include toc.html html=content%}
        </div>
    </div>
```

**Expected TOC**

```html
<ul>
    <li><\li>
    <li><\li>
    <li><\li>
    ....
<\ul>
```

**Actual TOC**

```html
  <ul>
    <li><\li>
    <li><\li>
<\ul>
<li><\li>
<li><\li>
<li><\li>
```

**Notes**

not only that problem, the css does not work either. for example:
```html
    <div class='col-md-2 col-xs-0'>
        <div class="toc">
          {% include toc.html html=content%}
        </div>
    </div>
```
```css
  .toc {
    padding: 10px;
    border-left: 2px solid #efefef;
    width: 280px;
    position: -webkit-sticky;
    position: sticky;
    top: 80px;
    margin-bottom: 80px;
    height: fit-content;
    margin-left: 30px;

    h2 {
      font-family: fantasy;
      color: #e32e00;
    }

    ul {
      margin-left: 20px;
      list-style-type: revert;
      font-size: 14px;
      line-height: 24px;
      color: #005b81;

      a {
        color: #005b81;

        &:hover {
          color: #e32e00;
          text-decoration: underline;
        }
      }
    }
  }
```

the css doesnt work. 
sorry that i don't know anything about php. :(
